/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:444734d6-436a-4dcc-87c1-7f81a1d6b8e7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jT97XeSeD",
    "aws_user_pools_web_client_id": "60hb04n8djd5b3fa8lj4vnovhg",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "biblestudybibleversionsee64d-master",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://m6mwwpjwszdf5kpzdq7loeltyi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-y3pikiulcza4die4rchngk6h3a",
    "aws_content_delivery_bucket": "biblestudybibleversionsb606f-dev-master",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d6m2wc03y50ar.cloudfront.net"
};


export default awsmobile;
